# Convolutional Neural Network

In [1]:
import matplotlib.pyplot as plt
from sklearn.datasets.samples_generator import make_blobs
import numpy as np

In [2]:
# buat fungsi sigmoid
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
# hyperparameter
# hyperparameter adalah parameter dimana kita dapat menentukan nilai epoch dan alpha (learning rate)
# train parameter adalah parameter hasil dari pelatihan dari machine learning

EPOCHS = 100
ALPHA = 0.01

# alpha adalah langkah untuk mencari minimum fungsi loss (gradient descent)

# generate data
(X,y)=make_blobs(n_samples=250,n_features=2, centers=2, cluster_std=1.05)

In [4]:
X[:5]

array([[-3.61941797,  6.75120539],
       [-5.42507161,  8.56631612],
       [-6.96700861,  5.44531279],
       [ 6.99974881,  2.90089274],
       [-7.58939614,  6.64313903]])

In [5]:
# tambahkan bias term pada X
X=np.c_[np.ones((X.shape[0])), X]

In [6]:
X[:5]

array([[ 1.        , -3.61941797,  6.75120539],
       [ 1.        , -5.42507161,  8.56631612],
       [ 1.        , -6.96700861,  5.44531279],
       [ 1.        ,  6.99974881,  2.90089274],
       [ 1.        , -7.58939614,  6.64313903]])

In [7]:
# inisialisasi Weight (W) dan list loss

# andaikan W adalah nilai random dari kumpulan angka yang menyebar uniform (seragam)
W=np.random.uniform(size=X.shape[1],)
# note : tambahkan ',' dibelakang, agar W menjadi format tuple, bukan float. 

# define losshistory sebagai array kosong
lossHistory = []

In [8]:
W

array([0.18422753, 0.63483444, 0.06703088])

In [9]:
# loop training sesuai epochs
for epoch in range(EPOCHS):
  pred = sigmoid (X.dot(W))
# X.dot(W) adalah perkalian matriks tanpa menggunakan looping masing-masing element

In [10]:
# loop training sesuai epochs

for epoch in range (EPOCHS):
  preds = sigmoid(X.dot(W))
  error = preds - y
  loss = np.sum(error ** 2)
  # ** pengertiannya adalah pangkat
  # loss seperti mencari squared error
  lossHistory.append(loss)

  print('epoch ke-{}, loss {}'.format(epoch+1, loss))

  gradient = X.T.dot(error) / X.shape[0]
  #T adalah transpose

  #update weight
  W = W - ALPHA*gradient

epoch ke-1, loss 0.4386541896964116
epoch ke-2, loss 0.42822629437941406
epoch ke-3, loss 0.41821768452474783
epoch ke-4, loss 0.4086053951389583
epoch ke-5, loss 0.3993680292858381
epoch ke-6, loss 0.39048563090387217
epoch ke-7, loss 0.381939569503694
epoch ke-8, loss 0.3737124354951006
epoch ke-9, loss 0.3657879450390952
epoch ke-10, loss 0.3581508534477093
epoch ke-11, loss 0.3507868762655683
epoch ke-12, loss 0.34368261726453103
epoch ke-13, loss 0.33682550266808226
epoch ke-14, loss 0.3302037209971499
epoch ke-15, loss 0.32380616799496076
epoch ke-16, loss 0.3176223961466826
epoch ke-17, loss 0.31164256836087656
epoch ke-18, loss 0.305857415425122
epoch ke-19, loss 0.3002581968883017
epoch ke-20, loss 0.2948366650575961
epoch ke-21, loss 0.2895850318298155
epoch ke-22, loss 0.2844959381047585
epoch ke-23, loss 0.27956242555326827
epoch ke-24, loss 0.2747779105349251
epoch ke-25, loss 0.2701361599801754
epoch ke-26, loss 0.2656312690694657
epoch ke-27, loss 0.2612576405578217
epoc

### APA YANG TERJADI JIKA : NAIKKAN EPOCHS DAN KECILKAN ALPHA ?

In [12]:
EPOCHS = 200
ALPHA = 0.001

W=np.random.uniform(size=X.shape[1],)
lossHistory = []

for epoch in range(EPOCHS):
  pred = sigmoid (X.dot(W))



for epoch in range (EPOCHS):
  preds = sigmoid(X.dot(W))
  error = preds - y
  loss = np.sum(error ** 2)
  lossHistory.append(loss)

  print('epoch ke-{}, loss {}'.format(epoch+1, loss))

  gradient = X.T.dot(error) / X.shape[0]

  W = W - ALPHA*gradient

epoch ke-1, loss 0.10215795793143749
epoch ke-2, loss 0.1020599912800218
epoch ke-3, loss 0.10196218148727451
epoch ke-4, loss 0.10186452820779121
epoch ke-5, loss 0.10176703109713153
epoch ke-6, loss 0.10166968981181634
epoch ke-7, loss 0.10157250400932427
epoch ke-8, loss 0.1014754733480888
epoch ke-9, loss 0.10137859748749442
epoch ke-10, loss 0.10128187608787395
epoch ke-11, loss 0.10118530881050516
epoch ke-12, loss 0.10108889531760769
epoch ke-13, loss 0.10099263527233976
epoch ke-14, loss 0.100896528338795
epoch ke-15, loss 0.10080057418199959
epoch ke-16, loss 0.10070477246790861
epoch ke-17, loss 0.10060912286340357
epoch ke-18, loss 0.10051362503628855
epoch ke-19, loss 0.10041827865528793
epoch ke-20, loss 0.1003230833900426
epoch ke-21, loss 0.1002280389111074
epoch ke-22, loss 0.1001331448899476
epoch ke-23, loss 0.1000384009989363
epoch ke-24, loss 0.09994380691135125
epoch ke-25, loss 0.09984936230137159
epoch ke-26, loss 0.09975506684407506
epoch ke-27, loss 0.099660920

**Terlihat bahwa saat kita naikkan epoch dan turunkan alpha, nilai loss akan semakin kecil. Namun, hal ini mungkin hanya terjadi di kasus ini saja. Bisa jadi, dikasus lain tidak. Oleh karena itu, EPOCHS dan ALPHA adalah hyperparameters yang dapat diubah sesuai dengan kondisi masalah.**